/*
 * Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

/* Auto-generated file.  DO NOT EDIT !! */
/* Generated by tafDiagGen tool version:  @  */

#include "configuration.hpp"
#include "legato.h"

#include <iostream>
#include <typeinfo>

namespace telux {
namespace tafsvc {
namespace cfg {

static Node root;
static bool root_inited = false;

EXPORT_SYM Node & get_root_node(void)
{
    NEED_INITED();
    return root;
}

EXPORT_SYM bool get_init_status(void)
{
    return root_inited;
}

EXPORT_SYM void diag_config_init(const char * cfg_path)
{
    boost::property_tree::json_parser::read_json(cfg_path, root);
    root_inited = true;
}

EXPORT_SYM Node & get_dtc_node(uint32_t dtc_code)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    for (auto & dtc: dtcs)
    {
        long this_dtc_code = std::stol(dtc.first);

        if ((uint32_t)this_dtc_code == dtc_code)
        {
            return dtc.second;
        }
    }

    throw std::runtime_error("Not found any [DTC node] matched DTC code.");
}

EXPORT_SYM Node & get_dtc_node(uint16_t event_id)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    uint16_t ev_id = 0;

    for (auto & dtc: dtcs)
    {
        Node & evl = dtc.second.get_child("events");

        for (auto & ev : evl)
        {
            ev_id = (uint16_t) std::stoi(ev.second.get_value<std::string>());

            /* Only match the first, event should be unique and mutually exclusive in each DTC */
            if (ev_id == event_id)
            {
                return dtc.second;
            }
        }
    }

    throw std::runtime_error("Not found any [dtc node] matched event id.");
}

EXPORT_SYM Node & get_event_node(uint16_t event_id)
{
    NEED_INITED();

    Node & evs = root.get_child("events");

    for (auto & ev: evs)
    {
        int this_event_id = std::stoi(ev.first);

        if ((uint16_t)this_event_id == event_id)
        {
            return ev.second;
        }
    }

    throw std::runtime_error("Not found any [event node] matched event id.");
}

EXPORT_SYM std::map<uint16_t, std::shared_ptr<Node>> get_event_nodes(uint32_t dtc_code)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    std::map<uint16_t, std::shared_ptr<Node>> ev_map;
    uint16_t ev_id = 0;

    for (auto & dtc: dtcs)
    {
        long this_dtc_code = std::stol(dtc.first);

        if ((uint32_t)this_dtc_code == dtc_code)
        {
            Node & evl = dtc.second.get_child("events");

            for (auto & ev : evl)
            {
                ev_id = (uint16_t) std::stoi(ev.second.get_value<std::string>());
                ev_map.insert(std::make_pair(ev_id, std::make_shared<Node>(get_event_node(ev_id))));
            }
        }
    }

    return ev_map;
}

EXPORT_SYM std::vector<uint16_t> get_event_ids(uint32_t dtc_code)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    std::vector<uint16_t> eid_list;
    uint16_t ev_id = 0;

    for (auto & dtc: dtcs)
    {
        long this_dtc_code = std::stol(dtc.first);

        if ((uint32_t)this_dtc_code == dtc_code)
        {
            Node & evl = dtc.second.get_child("events");

            for (auto & ev : evl)
            {
                ev_id = (uint16_t) std::stoi(ev.second.get_value<std::string>());
                eid_list.push_back(ev_id);
            }
        }
    }

    return eid_list;
}

EXPORT_SYM std::map<uint32_t, std::shared_ptr<Node>> get_dtc_nodes(void)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    std::map<uint32_t, std::shared_ptr<Node>> dtc_map;
    uint32_t dtc_code = 0;

    for (auto & dtc: dtcs)
    {
        dtc_code = (uint32_t) std::stol(dtc.first);
        dtc_map.insert(std::make_pair(dtc_code, std::make_shared<Node>(dtc.second)));
    }

    return dtc_map;
}

EXPORT_SYM std::vector<uint32_t> get_dtc_codes(void)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    std::vector<uint32_t> dtc_code_list;
    uint32_t dtc_code = 0;

    for (auto & dtc: dtcs)
    {
        dtc_code = (uint32_t) std::stol(dtc.first);
        dtc_code_list.push_back(dtc_code);
    }

    return dtc_code_list;
}

EXPORT_SYM size_t get_did_value_size(uint16_t did_code)
{
    NEED_INITED();

    Node & dids = root.get_child("did_all");

    for (auto & did: dids)
    {
        uint16_t this_did_code = (uint16_t) std::stol(did.first);
        if (this_did_code == did_code)
        {
            return (size_t) did.second.get<int>("implementation.did_size");
        }
    }

    throw std::runtime_error("Not found any [did node] matched did code.");
}

EXPORT_SYM std::map<std::string, uint8_t> get_diagnostic_session_map(void)
{
    NEED_INITED();

    Node & sessions = root.get_child("diagnostic_session");

    std::map<std::string, uint8_t> sess_map;

    for (auto & sess: sessions)
    {
        /* std::string sess_name = sess.second.get<std::string>("short_name"); */
        std::string sess_name = sess.first;
        uint8_t sess_id = sess.second.get<uint8_t>("id");

        sess_map.insert(std::make_pair(sess_name, sess_id));
    }

    return sess_map;
}

EXPORT_SYM uint8_t get_nrc_by_condition_id(uint8_t cond_id)
{
    switch(cond_id)
    {
        case Condition_tooHigh /* 1 / 0x01 */: return 0x22;
        case Condition_tooLow /* 2 / 0x02 */: return 0x22;
        case Condition_tooBig /* 3 / 0x03 */: return 0x22;
        case Condition_toSmall /* 4 / 0x04 */: return 0x22;
        case Condition_vehicleSpeedBodyEqual0 /* 5 / 0x05 */: return 0x88;
        case Condition_vehiclePowerModeEqualLifeOnBoard /* 6 / 0x06 */: return 0x83;
    }

    throw std::runtime_error("Not found any [NRC] matched condtion id.");
}

EXPORT_SYM uint8_t get_security_level_id(std::string level_name)
{
    /* diagnostic_session_security_level */

    NEED_INITED();

    Node & levels = root.get_child("diagnostic_session_security_level");

    uint8_t level_id = 0;

    for (auto & level: levels)
    {
        if (level.first == level_name)
        {
            level_id = level.second.get<uint8_t>("request_seed_id");
            break;
        }
    }

    if (level_id == 0)
        throw std::runtime_error("Not found level name: " + level_name);

    return level_id;
}

static const std::map<std::string, std::vector<uint8_t>> pattern_maps =
{
    { "base", {
        4, /* --> session */
        0x01, /* default_session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        0x52, /* download_emulated_session */
        0 /* --> security_level */
        } },
    { "did_read_app", {
        2, /* --> session */
        0x01, /* default_session */
        0x03, /* extended_diagnostic_session */
        0 /* --> security_level */
        } },
    { "secured_configuration", {
        3, /* --> session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        0x52, /* download_emulated_session */
        1, /* --> security_level */
        0x01, /* SecAcc_Level_01 */
        } },
    { "io_control", {
        1, /* --> session */
        0x03, /* extended_diagnostic_session */
        1, /* --> security_level */
        0x01, /* SecAcc_Level_01 */
        } },
    { "supplier_specific_security_level", {
        2, /* --> session */
        0x02, /* programming_session */
        0x60, /* system_supplier_specific_session */
        1, /* --> security_level */
        0x61, /* SecAcc_Level_61 */
        } },
    { "test_did_0xA0A0_r", {
        3, /* --> session */
        0x01, /* default_session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        0 /* --> security_level */
        } },
    { "test_did_0xA0A0_w", {
        2, /* --> session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        1, /* --> security_level */
        0x01, /* SecAcc_Level_01 */
        } },
    { "test_did_0xA0A1_r", {
        2, /* --> session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        2, /* --> security_level */
        0x01, /* SecAcc_Level_01 */
        0x61, /* SecAcc_Level_61 */
        } },
    { "test_did_0xA0A1_w", {
        2, /* --> session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        1, /* --> security_level */
        0x61, /* SecAcc_Level_61 */
        } },
    { "precheck_to_default_session", {
        5, /* --> session */
        0x01, /* default_session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        0x60, /* system_supplier_specific_session */
        0x52, /* download_emulated_session */
        0 /* --> security_level */
        } },
    { "precheck_to_programming_session", {
        3, /* --> session */
        0x01, /* default_session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        0 /* --> security_level */
        } },
    { "precheck_to_extended_diagnostic_session", {
        5, /* --> session */
        0x01, /* default_session */
        0x02, /* programming_session */
        0x03, /* extended_diagnostic_session */
        0x60, /* system_supplier_specific_session */
        0x52, /* download_emulated_session */
        0 /* --> security_level */
        } },
    { "precheck_to_download_emulated_session", {
        2, /* --> session */
        0x03, /* extended_diagnostic_session */
        0x52, /* download_emulated_session */
        1, /* --> security_level */
        0x01, /* SecAcc_Level_01 */
        } },
    { "precheck_to_system_supplier_specific_session", {
        2, /* --> session */
        0x02, /* programming_session */
        0x60, /* system_supplier_specific_session */
        1, /* --> security_level */
        0x61, /* SecAcc_Level_61 */
        } }
};

static std::string get_pattern(uint8_t session_id)
{
    std::string pattern;

    Node & sessions = root.get_child("diagnostic_session");

    for (auto & sess: sessions)
    {
        uint8_t sess_id = sess.second.get<uint8_t>("id");

        if (sess_id == session_id)
        {
            pattern = sess.second.get<std::string>("execution_authorization_pattern");
            break;
        }
    }

    return pattern;
}

EXPORT_SYM std::shared_ptr<std::vector<uint8_t>> get_pattern_sessions_by_session_id(uint8_t session_id)
{
    NEED_INITED();

    std::shared_ptr<std::vector<uint8_t>> session_list = std::make_shared<std::vector<uint8_t>>();
    std::string pattern = get_pattern(session_id);

    for (auto & pnode: pattern_maps)
    {
        if (pnode.first == pattern)
        {
            uint8_t total = pnode.second[0]; /* The number of sessions */

            for (int i = 0; i < total; i++)
            {
                session_list->push_back(pnode.second[i+1]); /* Index from 1 */
            }

            break;
        }
    }

    return session_list;
}

EXPORT_SYM std::shared_ptr<std::vector<uint8_t>> get_pattern_levels_by_session_id(uint8_t session_id)
{
    NEED_INITED();

    std::shared_ptr<std::vector<uint8_t>> level_list = std::make_shared<std::vector<uint8_t>>();
    std::string pattern = get_pattern(session_id);

    for (auto & pnode: pattern_maps)
    {
        if (pnode.first == pattern)
        {
            uint8_t total_of_sessions = pnode.second[0]; /* The number of sessions */

             /* [total-of-sess, sess_1, sess2, .. , tatal-of-level, level_1, level_2] */
            uint8_t total_of_levels = pnode.second[total_of_sessions + 1];

            for (int i = 0; i < total_of_levels; i++)
            {
                level_list->push_back(pnode.second[total_of_sessions + i + 1]); /* Index from total_of_sessions + 1 */
            }

            break;
        }
    }

    return level_list;
}

}
}
}

COMPONENT_INIT
{
    LE_INFO("Diagnostic Configuration Inited (v:%s, t:%s)",
            tafDiagGen_tool_version,
            tafDiagGen_tool_timestamp);
}
