/*
 * Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

/* Auto-generated file.  DO NOT EDIT !! */
/* Generated by tafDiagGen tool version:  @  */

#include "configuration.hpp"
#include "legato.h"

#include <iostream>
#include <typeinfo>

namespace telux {
namespace tafsvc {
namespace cfg {

static Node root;
static bool root_inited = false;

EXPORT_SYM Node & get_root_node(void)
{
    NEED_INITED();
    return root;
}

EXPORT_SYM bool get_init_status(void)
{
    return root_inited;
}

EXPORT_SYM void diag_config_init(const char * cfg_path)
{
    boost::property_tree::json_parser::read_json(cfg_path, root);
    root_inited = true;
}

EXPORT_SYM Node & get_dtc_node(uint32_t dtc_code)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    for (auto & dtc: dtcs)
    {
        long this_dtc_code = std::stol(dtc.first);

        if ((uint32_t)this_dtc_code == dtc_code)
        {
            return dtc.second;
        }
    }

    throw std::runtime_error("Not found any [DTC node] matched DTC code.");
}

EXPORT_SYM Node & get_dtc_node(uint16_t event_id)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    uint16_t ev_id = 0;

    for (auto & dtc: dtcs)
    {
        Node & evl = dtc.second.get_child("events");

        for (auto & ev : evl)
        {
            ev_id = (uint16_t) std::stoi(ev.second.get_value<std::string>());

            /* Only match the first, event should be unique and mutually exclusive in each DTC */
            if (ev_id == event_id)
            {
                return dtc.second;
            }
        }
    }

    throw std::runtime_error("Not found any [dtc node] matched event id.");
}

EXPORT_SYM Node & get_event_node(uint16_t event_id)
{
    NEED_INITED();

    Node & evs = root.get_child("events");

    for (auto & ev: evs)
    {
        int this_event_id = std::stoi(ev.first);

        if ((uint16_t)this_event_id == event_id)
        {
            return ev.second;
        }
    }

    throw std::runtime_error("Not found any [event node] matched event id.");
}

EXPORT_SYM std::map<uint16_t, std::shared_ptr<Node>> get_event_nodes(uint32_t dtc_code)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    std::map<uint16_t, std::shared_ptr<Node>> ev_map;
    uint16_t ev_id = 0;

    for (auto & dtc: dtcs)
    {
        long this_dtc_code = std::stol(dtc.first);

        if ((uint32_t)this_dtc_code == dtc_code)
        {
            Node & evl = dtc.second.get_child("events");

            for (auto & ev : evl)
            {
                ev_id = (uint16_t) std::stoi(ev.second.get_value<std::string>());
                ev_map.insert(std::make_pair(ev_id, std::make_shared<Node>(get_event_node(ev_id))));
            }
        }
    }

    return ev_map;
}

EXPORT_SYM std::vector<uint16_t> get_event_ids(uint32_t dtc_code)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    std::vector<uint16_t> eid_list;
    uint16_t ev_id = 0;

    for (auto & dtc: dtcs)
    {
        long this_dtc_code = std::stol(dtc.first);

        if ((uint32_t)this_dtc_code == dtc_code)
        {
            Node & evl = dtc.second.get_child("events");

            for (auto & ev : evl)
            {
                ev_id = (uint16_t) std::stoi(ev.second.get_value<std::string>());
                eid_list.push_back(ev_id);
            }
        }
    }

    return eid_list;
}

EXPORT_SYM std::map<uint32_t, std::shared_ptr<Node>> get_dtc_nodes(void)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    std::map<uint32_t, std::shared_ptr<Node>> dtc_map;
    uint32_t dtc_code = 0;

    for (auto & dtc: dtcs)
    {
        dtc_code = (uint32_t) std::stol(dtc.first);
        dtc_map.insert(std::make_pair(dtc_code, std::make_shared<Node>(dtc.second)));
    }

    return dtc_map;
}

EXPORT_SYM std::vector<uint32_t> get_dtc_codes(void)
{
    NEED_INITED();

    Node & dtcs = root.get_child("dtc_all");

    std::vector<uint32_t> dtc_code_list;
    uint32_t dtc_code = 0;

    for (auto & dtc: dtcs)
    {
        dtc_code = (uint32_t) std::stol(dtc.first);
        dtc_code_list.push_back(dtc_code);
    }

    return dtc_code_list;
}

EXPORT_SYM size_t get_did_value_size(uint16_t did_code)
{
    NEED_INITED();

    Node & dids = root.get_child("did_all");

    for (auto & did: dids)
    {
        uint16_t this_did_code = (uint16_t) std::stol(did.first);
        if (this_did_code == did_code)
        {
            return (size_t) did.second.get<int>("implementation.did_size");
        }
    }

    throw std::runtime_error("Not found any [did node] matched did code.");
}

EXPORT_SYM std::map<std::string, uint8_t> get_diagnostic_session_map(void)
{
    NEED_INITED();

    Node & sessions = root.get_child("diagnostic_session");

    std::map<std::string, uint8_t> sess_map;

    for (auto & sess: sessions)
    {
        /* std::string sess_name = sess.second.get<std::string>("short_name"); */
        std::string sess_name = sess.first;
        uint8_t sess_id = sess.second.get<uint8_t>("id");

        sess_map.insert(std::make_pair(sess_name, sess_id));
    }

    return sess_map;
}

EXPORT_SYM uint8_t get_nrc_by_condition_id(uint8_t cond_id)
{
    switch(cond_id)
    {
        case Condition_distanceTotalizerLowerOrEqual500km /* 1 / 0x01 */: return 0x22;
        case Condition_mileageForNormalModeFalse /* 2 / 0x02 */: return 0x22;
        case Condition_GADELowerOrEqualSWUpdateModeStatus /* 3 / 0x03 */: return 0x22;
        case Condition_GADELowerOrEqualMissionModeStatus /* 4 / 0x04 */: return 0x22;
        case Condition_GADEEqualMissionModeStatus /* 5 / 0x05 */: return 0x22;
        case Condition_GADEEqualUnavailableStatus /* 6 / 0x06 */: return 0x22;
        case Condition_vehicleSpeedBodyEqual0 /* 7 / 0x07 */: return 0x88;
        case Condition_vehicleSpeedBodyEqual0InPreviousMinute /* 8 / 0x08 */: return 0x88;
        case Condition_vehiclePowerModeEqualLifeOnBoard /* 9 / 0x09 */: return 0x83;
        case Condition_externalPowerSupplyConnected /* 10 / 0x0A */: return 0x22;
        case Condition_vehiclePowerModeEqualPowerOn /* 11 / 0x0B */: return 0x22;
        case Condition_callBackTimeoutNotInProgress /* 12 / 0x0C */: return 0x22;
        case Condition_vinEmpty /* 13 / 0x0D */: return 0x22;
        case Condition_updatableElementsActivated /* 14 / 0x0E */: return 0x22;
        case Condition_updatableElementsInstalled /* 15 / 0x0F */: return 0x22;
    }

    throw std::runtime_error("Not found any [NRC] matched condtion id.");
}

EXPORT_SYM uint8_t get_security_level_id(std::string level_name)
{
    /* diagnostic_session_security_level */

    NEED_INITED();

    Node & levels = root.get_child("diagnostic_session_security_level");

    uint8_t level_id = 0;

    for (auto & level: levels)
    {
        if (level.first == level_name)
        {
            level_id = level.second.get<uint8_t>("request_seed_id");
            break;
        }
    }

    if (level_id == 0)
        throw std::runtime_error("Not found level name: " + level_name);

    return level_id;
}

}
}
}

COMPONENT_INIT
{
    LE_INFO("Diagnostic Configuration Inited (v:%s, t:%s)",
            tafDiagGen_tool_version,
            tafDiagGen_tool_timestamp);
}
