# Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

ARG UBUNTU_DISTRO_ORIGIN
FROM $UBUNTU_DISTRO_ORIGIN

RUN apt-get -qq update
RUN apt-get -y install sudo
RUN apt-get update --fix-missing

RUN apt-get -y --no-install-recommends install ca-certificates
RUN update-ca-certificates
RUN apt-get -y --no-install-recommends install build-essential
RUN apt-get -y --no-install-recommends install curl
RUN apt-get -y --no-install-recommends install python3
RUN apt-get -y --no-install-recommends install ninja-build
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install python3-jinja2
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install cmake
RUN apt-get -y --no-install-recommends install python-setuptools
RUN apt-get -y --no-install-recommends install python2
RUN apt-get -y --no-install-recommends install git
RUN apt-get -y --no-install-recommends install fakeroot
RUN apt-get -y --no-install-recommends install file
RUN apt-get -y --no-install-recommends install libcap-dev
RUN apt-get -y --no-install-recommends install libssl-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install wget
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install git
RUN apt-get -y --no-install-recommends install python2-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install unzip
RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install openjdk-8-jre

RUN apt-get -y --no-install-recommends install python3-pip
RUN apt-get -y --no-install-recommends install python3-venv
RUN /usr/bin/python3 -m venv /venv
ENV PATH=/venv/bin:$PATH
RUN python3 -m pip install doipclient==1.1.1
RUN python3 -m pip install udsoncan==1.17.1
RUN python3 -m pip install pyyaml==6.0.1
RUN python3 -m pip install MarkupSafe==2.0.1
RUN python3 -m pip install Jinja2==3.0.3

RUN apt-get -y --no-install-recommends install pkg-config
RUN apt-get -y --no-install-recommends install libsqlite3-dev
RUN apt-get -y --no-install-recommends install libasound2-dev
RUN apt-get -y --no-install-recommends install nano

# Note that the order of the installation, put those after python3 virtual environment
# MakeTool 'ifgen' just depend on python version 2, keep it.
RUN apt-get -y --no-install-recommends install python-pip
RUN python2 -m pip install jinja2

ARG DEVELOPER_UID=1000
ARG DEVELOPER_GID=1000

# Create a non-root user: [developer] for development, with password: [simula]
RUN addgroup --gid $DEVELOPER_GID developer && \
    adduser --uid $DEVELOPER_UID --ingroup developer --home /home/developer \
            --shell /bin/bash --disabled-password --gecos "" developer

RUN adduser developer sudo
RUN echo 'developer:simula' | chpasswd
RUN echo 'developer ALL=(ALL:ALL) ALL' >> /etc/sudoers

# Configure fixuid for dynamic uid/gid passing.
RUN USER=developer && \
    GROUP=developer && \
    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4.1/fixuid-0.4.1-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\npaths:\n  - /tmp\n" > /etc/fixuid/config.yml

WORKDIR /home/developer/
USER developer

RUN echo 'if [ "`id -u`" -eq 0 ]; then PS1="[Build Your Simulation] \\u:\\w # "; else PS1="[Build Your Simulation] \\u:\\w $ "; fi' >> ~/.bashrc
ENTRYPOINT ["/bin/bash", "/home/developer/simulation_ro/scripts/forward_to_container.sh"]

# You should pass arguments such as : '-u $(id -u):$(id -g)' to 'docker run' command.
# Caution: please MOUNT your opensource project at the special location.
# ENTRYPOINT ["/usr/local/bin/fixuid", "-q", "/home/developer/simulation_ro/scripts/forward_to_container.sh"]
