#!/usr/bin/env python3
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
#
# generate_telaf_selinux.py
#
# Generate skeleton SELinux te/fc/if files for a TelAF app from its .adef file.
#
# Usage:
#   python3 generate_telaf_selinux.py --adef <path/to/AppName.adef> --output <output_dir>
#
# Output:
#   <output_dir>/AppName.te
#   <output_dir>/AppName.fc
#   <output_dir>/AppName.if   (copyright header only)

import argparse
import json
import os
import re
import sys

# ---------------------------------------------------------------------------
# Copyright header
# ---------------------------------------------------------------------------
COPYRIGHT = """\
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear
"""

# Appended to the copyright block in every generated file.
GENERATED_NOTICE = """\
# This file was auto-generated by generate_telaf_selinux.py as an initial
# skeleton based on the corresponding .adef file.  It covers the minimum
# rules derived from the adef (capabilities, IPC bindings, data files).
# Review and extend it with any additional rules required at runtime before
# committing.
"""

# ---------------------------------------------------------------------------
# Linux capability -> SELinux capability mapping
#
# capability  -> self:capability  { ... }
# capability2 -> self:capability2 { ... }
#
# CAP_WAKE_ALARM / CAP_BLOCK_SUSPEND are in capability2 class.
# All others are in capability class.
# ---------------------------------------------------------------------------
CAPABILITY2 = {
    "CAP_MAC_OVERRIDE",
    "CAP_MAC_ADMIN",
    "CAP_SYSLOG",
    "CAP_WAKE_ALARM",
    "CAP_BLOCK_SUSPEND",
    "CAP_AUDIT_READ",
    "CAP_PERFMON",
    "CAP_BPF",
    "CAP_CHECKPOINT_RESTORE",
}

CAP_NAME_OVERRIDES = {
    "CAP_SYSLOG": "syslog",
}


def map_capability(cap):
    """Map Linux CAP_XXX to SELinux capability/capability2 name."""
    selinux_name = CAP_NAME_OVERRIDES.get(cap, cap.removeprefix("CAP_").lower())
    selinux_class = "capability2" if cap in CAPABILITY2 else "capability"
    return selinux_class, selinux_name

# ---------------------------------------------------------------------------
# Known <tafcore> binding targets -> te interface calls
# ---------------------------------------------------------------------------
TAFCORE_BINDING_MAP = {
    "le_cfg":       "telaf_use_config_tree",
    "le_cfgAdmin":  "telaf_use_config_tree",
    "le_appInfo":   "telaf_app_read_proc_state",
    "le_update":    "telaf_use_device_manager",
    "le_appCtrl":   "telaf_use_device_manager",
    "le_appRemove": "telaf_use_device_manager",
    "le_framework": "telaf_use_service_directory",
    # le_wdog, le_instStat, le_wdog -> no extra rule needed
}

# ---------------------------------------------------------------------------
# adef parser
# ---------------------------------------------------------------------------

def _strip_comment(line):
    """Remove // and # inline comments."""
    line = re.sub(r'//.*', '', line)
    line = re.sub(r'#(?!\s*if\b).*', '', line)
    return line.strip()


def _parse_bundle_target(line):
    """
    Return the target path from a bundles.file entry.

    Supported forms include:
      [r] source/path /target/path
      source/path /target/path
      [r] source/path
      source/path

    If no target path is specified, Legato places the file at /<basename>.
    """
    tokens = line.split()
    if not tokens:
        return None
    if re.match(r'^\[[^\]]+\]$', tokens[0]):
        tokens = tokens[1:]
    if not tokens:
        return None

    target = tokens[1] if len(tokens) >= 2 else '/' + os.path.basename(tokens[0])
    if not target.startswith('/'):
        target = '/' + target
    return os.path.normpath(target).replace(os.sep, '/')


def parse_adef(path):
    """
    Parse an adef file and return a dict:
    {
        'app_name': str,
        'executables': [str, ...],          # exe names in declaration order
        'capabilities': [str, ...],         # CAP_XXX, excluding TEST_COVERAGE-only ones
        'bindings': [                        # (exe_name, api, target_app, target_api)
            ('tafFooSvc', 'taf_pm', 'tafPMSvc', 'taf_pm'),
            ('tafFooSvc', 'le_cfg', '<tafcore>', 'le_cfg'),
            ...
        ],
        'externs': [                         # (exe_name, api)
            ('tafFooSvc', 'taf_foo'),
            ...
        ],
        'bundle_files': [str, ...],          # target paths under read-only app root
        'requires_configtree': bool,
        'vsomeip': bool,                    # any VSOMEIP_CONFIGURATION* envvar present
    }
    """
    app_name = os.path.splitext(os.path.basename(path))[0]

    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        lines = f.readlines()

    executables = []
    capabilities = []
    bindings = []
    externs = []
    bundle_files = []
    requires_configtree = False
    vsomeip = False

    # --- state machine ---
    block_stack = []          # stack of current block names
    in_test_coverage = False  # inside #if TEST_COVERAGE block

    i = 0
    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()

        # Handle #if TEST_COVERAGE guard
        if re.match(r'#\s*if\s+\$\{LE_CONFIG_TEST_COVERAGE\}', stripped):
            in_test_coverage = True
            i += 1
            continue
        if in_test_coverage and re.match(r'#\s*endif', stripped):
            in_test_coverage = False
            i += 1
            continue

        # Skip lines inside TEST_COVERAGE block
        if in_test_coverage:
            i += 1
            continue

        # Skip other preprocessor lines
        if stripped.startswith('#'):
            i += 1
            continue

        line = _strip_comment(raw)
        if not line:
            i += 1
            continue

        # Track block open/close
        current_block = block_stack[-1] if block_stack else None

        # Detect requires.configTree before treating configTree: as a nested block.
        if current_block == 'requires' and (
            re.match(r'^configTree\s*:', line) or re.match(r'^configTree\s*$', line)
        ):
            requires_configtree = True

        # Block open: "keyword:" or "keyword: {" or standalone "{"
        block_open_match = re.match(r'^(\w+)\s*:\s*\{?$', line) or re.match(r'^(\w+)\s*:\s*$', line)
        if block_open_match and '{' not in line:
            # keyword: without brace on same line -> next non-empty line should have {
            block_stack.append(block_open_match.group(1))
            i += 1
            continue
        if block_open_match and '{' in line:
            block_stack.append(block_open_match.group(1))
            i += 1
            continue
        if line == '{':
            # bare { — keep current block context (sub-block)
            i += 1
            continue
        if line == '}':
            if block_stack:
                block_stack.pop()
            i += 1
            continue

        # ---- executables block ----
        if current_block == 'executables':
            # Format: exe_name = ( ... )
            m = re.match(r'^(\w+)\s*=', line)
            if m:
                executables.append(m.group(1))

        # ---- capability block ----
        elif current_block == 'capability':
            m = re.match(r'^(CAP_\w+)', line)
            if m:
                capabilities.append(m.group(1))

        # ---- bindings block ----
        elif current_block == 'bindings':
            # exe.comp.api -> target.api
            m = re.match(r'^(\w+)\.\w+\.(\w+)\s*->\s*(\S+)\.(\w+)', line)
            if m:
                exe_name   = m.group(1)
                client_api = m.group(2)
                target_app = m.group(3)
                target_api = m.group(4)
                bindings.append((exe_name, client_api, target_app, target_api))

        # ---- extern block ----
        elif current_block == 'extern':
            # Format: exe.comp.api
            m = re.match(r'^(\w+)\.\w+\.(\w+)', line)
            if m:
                externs.append((m.group(1), m.group(2)))

        # ---- bundles.file block ----
        elif current_block == 'file' and len(block_stack) >= 2 and block_stack[-2] == 'bundles':
            target = _parse_bundle_target(line)
            if target and target not in bundle_files:
                bundle_files.append(target)

        # ---- envVars block ----
        elif current_block == 'envVars':
            if re.match(r'^VSOMEIP_CONFIGURATION', line):
                vsomeip = True

        i += 1

    return {
        'app_name':           app_name,
        'executables':        executables,
        'capabilities':       capabilities,
        'bindings':           bindings,
        'externs':            externs,
        'bundle_files':       bundle_files,
        'requires_configtree': requires_configtree,
        'vsomeip':            vsomeip,
    }


# ---------------------------------------------------------------------------
# Capability rules generator
# ---------------------------------------------------------------------------

def build_capability_rules(exe_name, capabilities):
    """
    Return list of te rule strings for the given capability list.
    Splits into capability vs capability2 classes.
    """
    cap1 = []
    cap2 = []
    for cap in capabilities:
        cls, selinux_name = map_capability(cap)
        if cls == 'capability':
            cap1.append(selinux_name)
        else:
            cap2.append(selinux_name)

    rules = []
    # Filter out comment lines for the allow statement
    real_cap1 = [c for c in cap1 if not c.startswith('#')]
    comments   = [c for c in cap1 if c.startswith('#')]
    for c in comments:
        rules.append(c)
    if real_cap1:
        caps_str = ' '.join(sorted(real_cap1))
        rules.append(f'allow telaf_{exe_name}_t self:capability {{ {caps_str} }};')
    if cap2:
        caps_str = ' '.join(sorted(cap2))
        rules.append(f'allow telaf_{exe_name}_t self:capability2 {{ {caps_str} }};')
    return rules


# ---------------------------------------------------------------------------
# Binding rules generator
# ---------------------------------------------------------------------------

def build_binding_rules(exe_name, bindings, app_name, api_index=None):
    """
    Return (gen_require_types, te_rule_lines) for bindings belonging to exe_name.
    gen_require_types: set of type strings needed in gen_require
    te_rule_lines: list of rule strings
    """
    api_index = api_index or {}
    gen_require_types = set()
    rules = []
    emitted_rules = set()
    emitted_interfaces = set()  # deduplicate telaf_use_config_tree etc.

    for (b_exe, _client_api, target_app, target_api) in bindings:
        if b_exe != exe_name:
            continue

        if target_app == '<tafcore>':
            iface = TAFCORE_BINDING_MAP.get(target_api)
            if iface and iface not in emitted_interfaces:
                rules.append(f'{iface}(telaf_{exe_name}_t)')
                emitted_interfaces.add(iface)
            # else: le_wdog / le_instStat / unknown tafcore api -> skip silently

        elif target_app.startswith('<'):
            # <telaf> or other system bindings -> skip
            pass

        else:
            # Regular TelAF app binding.  Resolve target app API to the
            # executable exporting that API; this is required for multi-exe apps.
            target_exe = api_index.get(f'{target_app}.{target_api}', target_app)
            target_type = f'telaf_{target_exe}_t'
            gen_require_types.add(target_type)
            rule = f'telaf_ipc_bind(telaf_{exe_name}_t, {target_type})'
            if rule not in emitted_rules:
                rules.append(rule)
                emitted_rules.add(rule)

    return gen_require_types, rules


# ---------------------------------------------------------------------------
# .te generator
# ---------------------------------------------------------------------------

def generate_te(info, app_name, api_index=None):
    lines = COPYRIGHT.rstrip().splitlines()
    lines.append('')
    lines += GENERATED_NOTICE.rstrip().splitlines()
    lines.append('')
    lines.append(f'policy_module({app_name}, 1.0)')
    lines.append('')

    executables = info['executables']
    capabilities = info['capabilities']
    bindings = info['bindings']
    vsomeip = info['vsomeip']
    requires_configtree = info['requires_configtree']

    api_index = api_index or {}

    # Collect all gen_require types needed for ipc_bind across all exes
    all_ext_types = set()
    for exe in executables:
        ext_types, _ = build_binding_rules(exe, bindings, app_name, api_index)
        all_ext_types |= ext_types

    if all_ext_types:
        lines.append("gen_require(`")
        for t in sorted(all_ext_types):
            lines.append(f'    type {t};')
        lines.append("')")
        lines.append('')

    if vsomeip:
        lines.append('# TODO: VSOMEIP_CONFIGURATION detected in adef.')
        lines.append('# Add vsomeip-specific SELinux rules manually if this app needs them.')
        lines.append('')

    for exe in executables:
        lines.append(f'# --- {exe} ---')
        lines.append(f'type telaf_{exe}_exec_t;')
        lines.append(f'files_type(telaf_{exe}_exec_t);')
        lines.append(f'type telaf_{exe}_t;')
        lines.append(f'type telaf_{exe}_data_t;')
        lines.append(f'files_type(telaf_{exe}_data_t);')
        lines.append('')

        # capability rules
        cap_rules = build_capability_rules(exe, capabilities)
        if cap_rules:
            for r in cap_rules:
                lines.append(r)
            lines.append('')

        # init domain
        lines.append(f'init_telaf_app_domain(telaf_{exe}_t, telaf_{exe}_exec_t)')

        # binding rules
        _, b_rules = build_binding_rules(exe, bindings, app_name, api_index)

        # requires configTree (deduplicate with binding-derived rule)
        if requires_configtree:
            rule = f'telaf_use_config_tree(telaf_{exe}_t)'
            if rule not in b_rules:
                b_rules.insert(0, rule)

        for r in b_rules:
            lines.append(r)

        # data + admin
        lines.append(
            f'telaf_manage_app_data_files(telaf_{exe}_t, telaf_{exe}_data_t)'
        )
        lines.append(f'telaf_admin_manage_all_files_perms(telaf_{exe}_exec_t)')
        lines.append('')

    return '\n'.join(lines).rstrip() + '\n'


# ---------------------------------------------------------------------------
# .fc generator
# ---------------------------------------------------------------------------

def generate_fc(info, app_name):
    lines = COPYRIGHT.rstrip().splitlines()
    lines.append('')
    lines += GENERATED_NOTICE.rstrip().splitlines()
    lines.append('')

    executables = info['executables']
    bundle_files = info['bundle_files']
    default_data_type = f'telaf_{executables[0]}_data_t'

    # One lib line per app
    lines.append(
        f'/legato/systems/current/appsWriteable/{app_name}/lib(/.*)?'
        f'    gen_context(system_u:object_r:telaf_lib_t,s0)'
    )

    for exe in executables:
        lines.append(
            f'/legato/systems/current/appsWriteable/{app_name}/bin/{exe}'
            f'    --    gen_context(system_u:object_r:telaf_{exe}_exec_t,s0)'
        )
        lines.append(
            f'/legato/apps/[^/]*/read-only/bin/{exe}'
            f'    --    gen_context(system_u:object_r:telaf_{exe}_exec_t,s0)'
        )

    for bundle_file in bundle_files:
        lines.append(
            f'/legato/apps/[^/]*/read-only{bundle_file}'
            f'    --    gen_context(system_u:object_r:{default_data_type},s0)'
        )
        lines.append(
            f'/legato/systems/current/appsWriteable/{app_name}{bundle_file}'
            f'    --    gen_context(system_u:object_r:{default_data_type},s0)'
        )

    return '\n'.join(lines).rstrip() + '\n'


# ---------------------------------------------------------------------------
# .if generator
# refpolicy doc/policy.xml generator requires every .if that exists to
# contain at least a ## <summary> doc tag, otherwise the generated
# <module> XML node is empty and fails DTD validation.
# ---------------------------------------------------------------------------

def generate_if(app_name):
    lines = COPYRIGHT.rstrip().splitlines()
    lines.append('')
    lines += GENERATED_NOTICE.rstrip().splitlines()
    lines.append('')
    lines.append(f'## <summary> {app_name} interface </summary>')
    lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description='Generate skeleton SELinux te/fc/if for a TelAF adef.')
    parser.add_argument('--adef', required=True, help='Path to the .adef file')
    parser.add_argument('--output', required=True, help='Output directory')
    parser.add_argument('--api-index', default='',
                        help='Optional JSON file mapping "App.api" to executable name')
    args = parser.parse_args()

    adef_path = args.adef
    output_dir = args.output

    if not os.path.isfile(adef_path):
        print(f'ERROR: adef not found: {adef_path}', file=sys.stderr)
        sys.exit(1)

    info = parse_adef(adef_path)
    app_name = info['app_name']
    api_index = {}
    if args.api_index:
        with open(args.api_index, 'r', encoding='utf-8') as f:
            api_index = json.load(f)

    if not info['executables']:
        print(f'WARNING: no executables found in {adef_path}, skipping.', file=sys.stderr)
        sys.exit(0)

    os.makedirs(output_dir, exist_ok=True)

    te_path = os.path.join(output_dir, f'{app_name}.te')
    fc_path = os.path.join(output_dir, f'{app_name}.fc')
    if_path = os.path.join(output_dir, f'{app_name}.if')

    with open(te_path, 'w', encoding='utf-8') as f:
        f.write(generate_te(info, app_name, api_index))
    with open(fc_path, 'w', encoding='utf-8') as f:
        f.write(generate_fc(info, app_name))
    with open(if_path, 'w', encoding='utf-8') as f:
        f.write(generate_if(app_name))

    print(f'Generated: {te_path}')
    print(f'Generated: {fc_path}')
    print(f'Generated: {if_path}')


if __name__ == '__main__':
    main()
