# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

version: '3'
services:

  telaf_simulation_develop_2004:
    build:
      context: .
      dockerfile: Dockerfile.2004.develop
    image: telaf_simulation_develop_2004:1.0.0

  telaf_simulation_runtime_2004:
    build:
      context: .
      dockerfile: Dockerfile.2004.runtime
    image: telaf_simulation_runtime_2004:1.0.0
