# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

ARG UBUNTU_DISTRO_ORIGIN
FROM $UBUNTU_DISTRO_ORIGIN

RUN apt-get -qq update
RUN apt-get -y install sudo
RUN apt-get update --fix-missing

RUN apt-get -y --no-install-recommends install ca-certificates
RUN update-ca-certificates
RUN apt-get -y --no-install-recommends install curl
RUN apt-get -y --no-install-recommends install build-essential
RUN apt-get -y --no-install-recommends install libssl-dev
RUN apt-get -y --no-install-recommends install coreutils
RUN apt-get -y --no-install-recommends install psmisc
RUN apt-get -y --no-install-recommends install policycoreutils
RUN apt-get -y --no-install-recommends install busybox-syslogd
RUN apt-get -y --no-install-recommends install kmod
RUN apt-get -y --no-install-recommends install file
RUN apt-get -y --no-install-recommends install openssh-client
RUN apt-get -y --no-install-recommends install openssh-server
RUN apt-get -y --no-install-recommends install network-manager
RUN apt-get -y --no-install-recommends install tree
RUN apt-get -y --no-install-recommends install net-tools
RUN apt-get -y --no-install-recommends install iproute2
RUN apt-get -y --no-install-recommends install iputils-ping
RUN apt-get -y --no-install-recommends install strace
RUN apt-get -y --no-install-recommends install cgroup-tools
RUN apt-get -y --no-install-recommends install python3
RUN apt-get -y --no-install-recommends install python2
RUN apt-get -y --no-install-recommends install less
RUN apt-get -y --no-install-recommends install gdb
RUN apt-get -y --no-install-recommends install tcpdump
RUN apt-get -y --no-install-recommends install lsb-release
RUN apt-get -y --no-install-recommends install libcap-dev


# Make root password to: [simula]
RUN echo 'root:simula' | chpasswd

WORKDIR /root

# Distinguish between container and host
ENV ON_TELAF_SIMULATION_DOCKER=yes
RUN echo "ON_TELAF_SIMULATION_DOCKER=yes" >> ~/.bashrc

# Injects the script of simulation
RUN echo 'if [ "`id -u`" -eq 0 ]; then PS1="[TelAF Simulation] \\u:\\w # "; else PS1="[TelAF Simulation] \\u:\\w $ "; fi' >> ~/.bashrc
RUN echo 'if [ -f $HOME/simulation/up_simulation.sh ]; then . $HOME/simulation/up_simulation.sh; else echo "Not found $HOME/simulation/up_simulation.sh --> NO simulation"; exit 0; fi' >> ~/.bashrc
